version: 0.1
os: linux
files:
  - source: /app
    destination: /ruby_apps/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 10
      runas: root
    - location: scripts/start_server
      timeout: 10
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 10
      runas: root

