# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 337e7841d3d0a85f467293574c30ca71ced35233a8e73897d8376066a5d4e5653e6a51d5f9be416e3628c1af608b82c926044affb477a6620b87e88a9c7c37ae

test:
  secret_key_base: 591e70f0f671e55d3e21c478e08420f47e98f88f401d814dc0716dd375eff1d5d05d765725fad6e4802e816bec7a56dc69dd6c8b57cb02f4984c52f840c54fb6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
